export const DEFAULT_HABITS = [
  // Body
  { id: "hb1", label: "Protein goal hit",           icon: "🥩", color: "#e8527a", bg: "#fbd7e1", goal: 7, section: "body" },
  { id: "hb2", label: "Workout done",                icon: "💪", color: "#7aaee5", bg: "#dceaf7", goal: 5, section: "body" },
  { id: "hb3", label: "Hydrated",                    icon: "💧", color: "#b39bd8", bg: "#ebe1f5", goal: 7, section: "body" },
  { id: "hb4", label: "Anti-inflammatory meal",      icon: "🥗", color: "#88b896", bg: "#d8ecdc", goal: 7, section: "body" },
  // Hair
  { id: "hh1", label: "Nightly hair protection",     icon: "🎀", color: "#f4a261", bg: "#fde3cf", goal: 7, section: "hair" },
  { id: "hh2", label: "Scalp treatment applied",     icon: "🌱", color: "#6db88a", bg: "#c8e8d4", goal: 7, section: "hair" },
  // Business
  { id: "hbs1", label: "School hours logged",        icon: "📚", color: "#9b7cc8", bg: "#e0d4f5", goal: 5, section: "business" },
  { id: "hbs2", label: "Silk Collective task done",  icon: "👑", color: "#f7c548", bg: "#fef3cd", goal: 5, section: "business" },
  // Mind & Recovery
  { id: "hm1", label: "Morning devotion",            icon: "🕊️", color: "#d68d84", bg: "#f8dad5", goal: 7, section: "mind" },
  { id: "hm2", label: "Screen-free wind down",       icon: "🌙", color: "#88b896", bg: "#d8ecdc", goal: 7, section: "mind" },
  { id: "hm3", label: "In bed on time",              icon: "😴", color: "#7aaee5", bg: "#dceaf7", goal: 7, section: "mind" },
];

export const DEFAULT_BUDGET = [
  { id: "b1", category: "Groceries", spent: 0, budget: 500, color: "var(--accent-2)" },
  { id: "b2", category: "Dining out", spent: 0, budget: 250, color: "var(--primary)" },
  { id: "b3", category: "Beauty + Self-care", spent: 0, budget: 200, color: "var(--accent-3)" },
  { id: "b4", category: "Fitness", spent: 0, budget: 150, color: "var(--accent-1)" },
  { id: "b5", category: "Books + Hobbies", spent: 0, budget: 100, color: "var(--accent-4)" },
  { id: "b6", category: "Subscriptions", spent: 0, budget: 90, color: "var(--accent-3)" },
];

export const DEFAULT_GYM_WEEK = [
  { day: "Mon", type: "Workout", done: false },
  { day: "Tue", type: "Workout", done: false },
  { day: "Wed", type: "Rest", done: false, rest: true },
  { day: "Thu", type: "Workout", done: false },
  { day: "Fri", type: "Workout", done: false },
  { day: "Sat", type: "Workout", done: false },
  { day: "Sun", type: "Rest", done: false, rest: true },
];

export const DEFAULT_MOOD_WEEK = [
  { day: "Mon", mood: 0, emoji: null },
  { day: "Tue", mood: 0, emoji: null },
  { day: "Wed", mood: 0, emoji: null },
  { day: "Thu", mood: 0, emoji: null },
  { day: "Fri", mood: 0, emoji: null },
  { day: "Sat", mood: 0, emoji: null },
  { day: "Sun", mood: 0, emoji: null },
];

export function getDefaultState() {
  return {
    page: "today",
    tasks: [],
    habits: DEFAULT_HABITS,
    habitLogs: {
      hb1:  [false, false, false, false, false, false, false],
      hb2:  [false, false, false, false, false, false, false],
      hb3:  [false, false, false, false, false, false, false],
      hb4:  [false, false, false, false, false, false, false],
      hh1:  [false, false, false, false, false, false, false],
      hh2:  [false, false, false, false, false, false, false],
      hbs1: [false, false, false, false, false, false, false],
      hbs2: [false, false, false, false, false, false, false],
      hm1:  [false, false, false, false, false, false, false],
      hm2:  [false, false, false, false, false, false, false],
      hm3:  [false, false, false, false, false, false, false],
    },
    weeklyHabitLogs: {},
    churchLog: {},
    agenda: [],
    gymWeek: DEFAULT_GYM_WEEK,
    cards: [],
    budget: DEFAULT_BUDGET,
    savings: [],
    activeQuarter: 'Q2-2026',
    quarterGoals: [
      // Q2 2026
      { id:'gq2h1', title:'Stay consistent on 8-week hair regimen', category:'health', status:'in_progress', progress:40, targetDate:'2026-06-30', notes:'', subtasks:[], carriedOver:false, quarter:'Q2-2026' },
      { id:'gq2h2', title:'Hit protein goal 5 of 7 days/week', category:'health', status:'in_progress', progress:50, targetDate:'2026-06-30', notes:'', subtasks:[], carriedOver:false, quarter:'Q2-2026' },
      { id:'gq2f1', title:'Formalize The Silk Collective LLC', category:'finance', status:'not_started', progress:0, targetDate:'2026-06-30', notes:'', subtasks:[], carriedOver:false, quarter:'Q2-2026' },
      { id:'gq2f2', title:'Open dedicated business checking account', category:'finance', status:'not_started', progress:0, targetDate:'2026-06-30', notes:'', subtasks:[], carriedOver:false, quarter:'Q2-2026' },
      { id:'gq2b1', title:'Maintain weekly content posting for both pages', category:'business', status:'in_progress', progress:45, targetDate:'2026-06-30', notes:'', subtasks:[], carriedOver:false, quarter:'Q2-2026' },
      { id:'gq2p1', title:'Trinidad trip', category:'personal', status:'on_track', progress:75, targetDate:'2026-06-25', notes:'', subtasks:[], carriedOver:false, quarter:'Q2-2026' },
      { id:'gq2p2', title:'Read 1 book this quarter', category:'personal', status:'in_progress', progress:30, targetDate:'2026-06-30', notes:'', subtasks:[], carriedOver:false, quarter:'Q2-2026' },
      // Q3 2026
      { id:'gq3h1', title:'Complete 8-week hair regimen', category:'health', status:'not_started', progress:0, targetDate:'2026-07-09', notes:'', subtasks:[], carriedOver:false, quarter:'Q3-2026' },
      { id:'gq3h2', title:'Attend scheduled trim and document length retained', category:'health', status:'not_started', progress:0, targetDate:'2026-07-23', notes:'', subtasks:[], carriedOver:false, quarter:'Q3-2026' },
      { id:'gq3h3', title:'Body recomposition photo check-in milestone', category:'health', status:'not_started', progress:0, targetDate:'2026-08-31', notes:'', subtasks:[], carriedOver:false, quarter:'Q3-2026' },
      { id:'gq3f1', title:'Review and raise Silk Collective pricing post-licensure', category:'finance', status:'not_started', progress:0, targetDate:'2026-08-01', notes:'', subtasks:[], carriedOver:false, quarter:'Q3-2026' },
      { id:'gq3f2', title:'Organize all business receipts for Schedule C', category:'finance', status:'not_started', progress:0, targetDate:'2026-09-30', notes:'', subtasks:[], carriedOver:false, quarter:'Q3-2026' },
      { id:'gq3f3', title:'Set and track quarterly salon revenue target', category:'finance', status:'not_started', progress:0, targetDate:'2026-09-30', notes:'', subtasks:[], carriedOver:false, quarter:'Q3-2026' },
      { id:'gq3b1', title:'Graduate cosmetology school', category:'business', status:'not_started', progress:0, targetDate:'2026-08-31', notes:'', subtasks:[{id:'st-b1a',text:'Complete remaining hours',done:false},{id:'st-b1b',text:'Pass state board exam',done:false},{id:'st-b1c',text:'Receive license',done:false}], carriedOver:false, quarter:'Q3-2026' },
      { id:'gq3b2', title:'Launch EDDM direct mail campaign', category:'business', status:'not_started', progress:0, targetDate:'2026-08-15', notes:'', subtasks:[], carriedOver:false, quarter:'Q3-2026' },
      { id:'gq3b3', title:'Build service menu and set up booking system', category:'business', status:'not_started', progress:0, targetDate:'2026-08-01', notes:'', subtasks:[], carriedOver:false, quarter:'Q3-2026' },
      { id:'gq3b4', title:'Hit monthly booking target (define number)', category:'business', status:'not_started', progress:0, targetDate:'2026-09-30', notes:'', subtasks:[], carriedOver:false, quarter:'Q3-2026' },
      { id:'gq3p1', title:'Graduate cosmetology school', category:'personal', status:'not_started', progress:0, targetDate:'2026-08-31', notes:'', subtasks:[], carriedOver:false, quarter:'Q3-2026' },
      { id:'gq3p2', title:'Read 4 books this quarter', category:'personal', status:'not_started', progress:0, targetDate:'2026-09-30', notes:'', subtasks:[], carriedOver:false, quarter:'Q3-2026' },
      { id:'gq3p3', title:'Plan next trip after Trinidad', category:'personal', status:'not_started', progress:0, targetDate:'2026-07-31', notes:'', subtasks:[], carriedOver:false, quarter:'Q3-2026' },
      { id:'gq3p4', title:'Mid-quarter content audit', category:'personal', status:'not_started', progress:0, targetDate:'2026-07-31', notes:'', subtasks:[], carriedOver:false, quarter:'Q3-2026' },
    ],
    parking: [],
    journal: [],
    brainDumps: [],
    moodLog: {},
    journalPin: null,
    recipes: [],
    content: [],
    transactions: [],
    moodWeek: DEFAULT_MOOD_WEEK,
    hair: {
      activeWeek: 5,
      currentStyle: 'natural',
      nightlyDone: {},
      nightlyDate: '',
      scalpDays: {},
      washDayLog: [],
      lengthLog: [{ date: new Date().toISOString().slice(0, 10), length: 15 }],
      templeNotes: '',
      progressPhotos: [],
    },
    fitness: {
      weightLog: [{ date: new Date().toISOString().slice(0, 10), weight: 160 }],
      measurements: { waist: 0, arms: 0, glutes: 0, hips: 0, date: '' },
      goals: { glutes: 30, arms: 20, core: 25, back: 20 },
      goalNotes: { glutes: '', arms: '', core: '', back: '' },
      targets: { calories: 1800, protein: 130, workoutsPerWeek: 3 },
      nutritionLog: [],
      workoutLog: [],
      watchWorkouts: [],
      sleepLog: [],
      progressPhotos: [],
    },
    focus: "",
    reflections: { wins: "", push: "" },
    groceryList: [],
    calendarUrls: [],
    show: {
      today: true,
      week: true,
      habits: true,
      quarter: true,
      finance: true,
      journal: true,
      recipes: true,
      content: true,
      hair: true,
      briefing: true,
      fitness: true,
      silk: true,
      travel: true,
      review: true,
      devotion: true,
    },
    scSetupChecklist: {
      phases: [
        { id: 'phase1', title: 'Legal Foundation', items: [
          { id: 'p1i1', text: 'File LLC Articles of Organization (Maryland)', done: false },
          { id: 'p1i2', text: 'Obtain a registered agent', done: false },
          { id: 'p1i3', text: 'EIN obtained', done: true, locked: true },
          { id: 'p1i4', text: 'Apply for Maryland state business license', done: false },
          { id: 'p1i5', text: 'Obtain cosmetology establishment license', done: false },
          { id: 'p1i6', text: 'Draft single-member LLC operating agreement', done: false },
        ]},
        { id: 'phase2', title: 'Financial Setup', items: [
          { id: 'p2i1', text: 'Open dedicated business checking account', done: false },
          { id: 'p2i2', text: 'Separate all business expenses from personal', done: false },
          { id: 'p2i3', text: 'Set up bookkeeping system (spreadsheet or software)', done: false },
          { id: 'p2i4', text: 'Understand quarterly estimated tax payment schedule', done: false },
          { id: 'p2i5', text: 'Finalize service menu with pricing', done: false },
          { id: 'p2i6', text: 'Write deposit and cancellation policy', done: false },
        ]},
        { id: 'phase3', title: 'Operations', items: [
          { id: 'p3i1', text: 'Choose and set up booking platform (Vagaro, GlossGenius, or Square)', done: false },
          { id: 'p3i2', text: 'Create client intake and consultation form', done: false },
          { id: 'p3i3', text: 'Write full policies document', done: false },
          { id: 'p3i4', text: 'Set up back bar inventory tracking', done: false },
          { id: 'p3i5', text: 'Confirm salon suite or home studio setup', done: false },
          { id: 'p3i6', text: 'Purchase professional liability insurance', done: false },
          { id: 'p3i7', text: 'Purchase general liability insurance', done: false },
        ]},
        { id: 'phase4', title: 'Brand & Presence', items: [
          { id: 'p4i1', text: 'Finalize logo and color palette', done: false },
          { id: 'p4i2', text: 'Optimize Instagram business profile', done: false },
          { id: 'p4i3', text: 'Optimize TikTok business profile', done: false },
          { id: 'p4i4', text: 'Set up Google Business Profile', done: false },
          { id: 'p4i5', text: 'Create booking link or simple website', done: false },
          { id: 'p4i6', text: 'Design digital service menu / rate card', done: false },
        ]},
        { id: 'phase5', title: 'Launch', items: [
          { id: 'p5i1', text: 'Make official launch announcement on both platforms', done: false },
          { id: 'p5i2', text: 'Send EDDM mail campaign', done: false },
          { id: 'p5i3', text: 'Book first 5 paid clients post-licensure', done: false },
          { id: 'p5i4', text: 'Collect 5 Google reviews in first 30 days', done: false },
          { id: 'p5i5', text: 'Set first monthly revenue goal', done: false },
          { id: 'p5i6', text: 'Schedule 30-day business review with yourself', done: false },
        ]},
      ],
    },
    scFinances: {
      revenue: [],
      expenses: [],
      revenueGoal: 3000,
      pricingMenu: [
        { id: 'pm1', name: 'Silk Press', duration: '2–3 hrs', priceMin: 95, priceMax: 110, notes: '' },
        { id: 'pm2', name: 'Quick Weave', duration: '2–3 hrs', priceMin: 130, priceMax: 150, notes: '' },
        { id: 'pm3', name: 'Silk Press + Trim', duration: '2.5–3.5 hrs', priceMin: 115, priceMax: 130, notes: '' },
        { id: 'pm4', name: 'Scalp Treatment', duration: '45–60 min', priceMin: 45, priceMax: 65, notes: '' },
        { id: 'pm5', name: 'Consultation', duration: '15 min', priceMin: 0, priceMax: 0, notes: 'Complimentary' },
      ],
      scheduleCTracked: {},
    },
    scClients: [],
    scReviews: [],
    scCampaigns: [
      { id: 'camp1', name: 'Summer Launch EDDM', type: 'EDDM', status: 'Planning', startDate: '2026-08-15', endDate: '', goal: 'Book 10 new clients in Silver Spring area', estimatedCost: 0, actualCost: 0, notes: '', linkedGoal: '' },
    ],
    scMarketingBudget: { monthly: 500, costPerClientLog: [] },
    scIdeasBank: [
      { id: 'idea1', title: 'Referral discount', type: 'Referral', cost: 'low', notes: 'Give $15 off to client who refers a new booking', status: 'Idea' },
      { id: 'idea2', title: 'First-time client offer', type: 'Promotion', cost: 'low', notes: '$10 off first silk press', status: 'Idea' },
      { id: 'idea3', title: 'Holiday glam season campaign', type: 'Paid Social', cost: 'medium', notes: 'Nov–Dec push', status: 'Idea' },
      { id: 'idea4', title: 'Back to school promotion', type: 'Promotion', cost: 'low', notes: 'August back-to-school energy', status: 'Idea' },
      { id: 'idea5', title: 'New Year New Look', type: 'Organic', cost: 'free', notes: 'January content + offer', status: 'Idea' },
      { id: 'idea6', title: 'Loyalty reward', type: 'Referral', cost: 'low', notes: 'Free deep conditioning after 5 visits', status: 'Idea' },
      { id: 'idea7', title: 'Bundle: Silk press + scalp treatment', type: 'Promotion', cost: 'low', notes: 'Package deal', status: 'Idea' },
      { id: 'idea8', title: 'Google review incentive', type: 'Promotion', cost: 'low', notes: '$5 off next visit for a review', status: 'Idea' },
    ],
    scContentCalendar: [],
    scContentIdeas: [],
    scHashtagSets: [
      { id: 'hs1', name: 'Silk Press Set', platform: 'Instagram', tags: '#silkpress #silkpresshair #naturalhair #dmvhair #marylandstylist #hairsalon #protectivestyles #blackhair #healthyhair #silkcollective' },
    ],
    scPlatformStats: { igFollowers: 0, tiktokFollowers: 0, igLastPost: '', tiktokLastPost: '', weeklyPostCount: 0, igTrend: [], tiktokTrend: [] },
    scBrandRef: {
      pillars: ['Transformations', 'Hair Education', 'Behind the Scenes', 'Promotions & Offers', 'Client Results', 'Business Journey'],
      voice: 'Honest and conversational. Not scripted or overly polished. Real and relatable.',
      audience: 'Women with textured hair in the DMV area, 25–45, value quality and education',
      editing: false,
    },
    scEducation: {
      ceHoursRequired: 4,
      ceLog: [],
      wishlist: [
        { id: 'wl1', name: 'Advanced Silk Press Techniques', topic: 'Technical Skills', provider: '', cost: '', priority: 'high', notes: '' },
        { id: 'wl2', name: 'Extension Methods', topic: 'Technical Skills', provider: '', cost: '', priority: 'high', notes: '' },
        { id: 'wl3', name: 'Business Finance for Stylists', topic: 'Business', provider: '', cost: '', priority: 'medium', notes: '' },
        { id: 'wl4', name: 'Instagram Growth for Beauty Professionals', topic: 'Marketing', provider: '', cost: '', priority: 'medium', notes: '' },
      ],
      completed: [],
      events: [
        { id: 'ev1', name: 'Bronner Bros International Beauty Show', date: '', location: 'Atlanta, GA', cost: '', registered: false, notes: '' },
        { id: 'ev2', name: "America's Beauty Show Chicago", date: '', location: 'Chicago, IL', cost: '', registered: false, notes: '' },
        { id: 'ev3', name: 'Baltimore Natural Hair Expo', date: '', location: 'Baltimore, MD', cost: '', registered: false, notes: '' },
      ],
    },
    scInventory: [],
    scPolicies: `DEPOSIT POLICY\nA 50% non-refundable deposit is required to book and secure your appointment. This deposit will be applied to your service total.\n\nCANCELLATION POLICY\nCancellations must be made at least 48 hours before your scheduled appointment. Cancellations within 48 hours will result in forfeiture of the deposit. If you need to reschedule, please reach out at least 48 hours in advance and I will do my best to accommodate you.\n\nLATE ARRIVALS\nThere is a 15-minute grace period for late arrivals. If you arrive more than 15 minutes late, your appointment may be rescheduled and your deposit forfeited. Please communicate if you are running behind.\n\nCHILDREN POLICY\nFor the safety and comfort of all clients, children are not permitted in the salon during your appointment unless they are also receiving a service.\n\nTOUCH-UP WINDOW\nComplimentary touch-ups are available within 7 days of your original service if there is a technical issue with the work performed. Touch-ups are not offered for natural hair changes or new styling requests.\n\nNO-SHOW POLICY\nNo-shows will forfeit their deposit and may be required to prepay in full for future bookings.`,
    scConsultationForm: [
      { id: 'cq1', text: 'What services are you interested in today?' },
      { id: 'cq2', text: 'What is your current hair care routine?' },
      { id: 'cq3', text: 'Have you had any chemical services in the last 6 months?' },
      { id: 'cq4', text: 'Do you have any product sensitivities or allergies?' },
      { id: 'cq5', text: 'What are your hair goals?' },
      { id: 'cq6', text: 'How do you typically maintain your hair between appointments?' },
      { id: 'cq7', text: 'Are there any concerns I should know about (scalp, breakage, thinning)?' },
    ],
    scWeeklyTodos: {},
    scBookingsThisWeek: 0,

    // ── Travel Hub ──────────────────────────────────────────────────────────
    travelTrips: [
      { id: 'trip1', destination: 'Trinidad', country: 'Trinidad & Tobago', departure: '2026-06-25', return: '2026-07-02', status: 'Confirmed', purpose: 'leisure', companions: '', accommodation: '', budget: 2000, itinerary: [], budgetBreakdown: { flights: 0, accommodation: 0, food: 0, activities: 0, shopping: 0, misc: 0 }, budgetActual: { flights: 0, accommodation: 0, food: 0, activities: 0, shopping: 0, misc: 0 }, packingItems: {}, visaChecks: {}, visaDetails: '', contentPlan: '', currencyNote: 'TTD — use Wise card, get ~$200 USD cash backup', memories: null },
      { id: 'trip2', destination: 'Rio de Janeiro', country: 'Brazil', departure: '2026-04-24', return: '2026-04-29', status: 'Complete', purpose: 'leisure', companions: '', accommodation: '', budget: 0, itinerary: [], budgetBreakdown: { flights: 0, accommodation: 0, food: 0, activities: 0, shopping: 0, misc: 0 }, budgetActual: { flights: 0, accommodation: 0, food: 0, activities: 0, shopping: 0, misc: 0 }, packingItems: {}, visaChecks: {}, visaDetails: '', contentPlan: '', currencyNote: '', memories: { favoriteMoment: '', bestMeal: '', wouldGoBack: 'yes', rating: 5, notes: '13-slide Instagram carousel created and posted', carouselPosted: true, carouselLink: '' } },
    ],
    travelPackingTemplates: [
      { id: 'tpl1', name: 'International Warm Weather', description: 'Beach and tropical destinations', categories: {
        Documents: ['Passport', 'Visa docs', 'Travel insurance card', 'Flight/hotel confirmations'],
        Clothing: ['Swimsuits (2)', 'Cover-up', 'Casual dresses (3)', 'One nice outfit', 'Shorts (2)', 'Comfortable walking shoes', 'Sandals', 'Light jacket'],
        Toiletries: ['SPF 50', 'After-sun lotion', 'Deodorant', 'Toothbrush/paste', 'Feminine care', 'Medications'],
        Hair: ['Satin bonnet', 'Edge control', 'Travel-size leave-in', 'Dry shampoo', 'Silk scarf', 'Small flat iron', 'Heat protectant'],
        Tech: ['Phone', 'Charger', 'Portable battery', 'Adapter (if needed)', 'Earbuds', 'Camera'],
        Misc: ['Reusable tote', 'Cash in local currency', 'Wise card', 'Small crossbody bag'],
      }},
      { id: 'tpl2', name: 'Domestic Weekend', description: 'Short domestic getaways', categories: {
        Clothing: ['Casual outfits (2)', 'One nice outfit', 'Comfortable shoes', 'Loungewear'],
        Toiletries: ['Deodorant', 'Toothbrush/paste', 'Skincare basics'],
        Hair: ['Satin bonnet', 'Edge control', 'Quick styling tool'],
        Tech: ['Phone', 'Charger', 'Earbuds'],
        Misc: ['Small bag', 'Cash', 'Card'],
      }},
    ],
    travelDocuments: { passportExpiry: '', ktn: '', frequentFlyer: '', insuranceProvider: '', policyNumber: '', emergencyContacts: '', airlines: '', notes: '' },

    // ── Monthly Review ───────────────────────────────────────────────────────
    monthlyReviews: {},

    // ── Devotion ─────────────────────────────────────────────────────────────
    devotionEntries: {},
    devotionPrayerRequests: [],
    devotionAffirmations: [
      { id: 'aff1', text: 'I am disciplined, focused, and intentional with my time and energy.', category: 'Identity', pinned: true },
      { id: 'aff2', text: 'My business is built on excellence and my clients feel that the moment they sit in my chair.', category: 'Business', pinned: false },
      { id: 'aff3', text: 'I honor my body with rest, movement, and nourishment.', category: 'Health', pinned: false },
      { id: 'aff4', text: 'I am walking in purpose. Every step I\'m taking right now is preparing me for what\'s next.', category: 'Faith', pinned: true },
      { id: 'aff5', text: 'I have the wisdom to manage everything I\'ve been given.', category: 'Identity', pinned: false },
      { id: 'aff6', text: 'I am fearfully and wonderfully made. God\'s fingerprints are all over my life.', category: 'Faith', pinned: false },
      { id: 'aff7', text: 'My steps are ordered. Even the detours are part of the plan.', category: 'Faith', pinned: false },
      { id: 'aff8', text: 'I don\'t have to figure everything out today. I trust God with what I cannot see.', category: 'Faith', pinned: false },
      { id: 'aff9', text: 'I am protected, provided for, and fully at peace.', category: 'Faith', pinned: false },
      { id: 'aff10', text: 'I am not behind. I am on God\'s timeline, which is always right on time.', category: 'Faith', pinned: false },
      { id: 'aff11', text: 'The Silk Collective is more than a business — it is a ministry to every woman who sits in my chair.', category: 'Business', pinned: false },
      { id: 'aff12', text: 'I charge what I\'m worth and I deliver beyond it every single time.', category: 'Business', pinned: false },
      { id: 'aff13', text: 'I am a licensed professional. I have earned every room I walk into.', category: 'Business', pinned: false },
      { id: 'aff14', text: 'I don\'t compete. I create. There is no one doing it exactly like me.', category: 'Business', pinned: false },
      { id: 'aff15', text: 'The woman I am becoming is being built right now — in the quiet, in the discipline, in the showing up.', category: 'Business', pinned: false },
      { id: 'aff16', text: 'I finish what I start. Graduation is already mine.', category: 'Identity', pinned: false },
      { id: 'aff17', text: 'Every hard day in school is an investment I am already profiting from.', category: 'Identity', pinned: false },
      { id: 'aff18', text: 'I am consistent, not perfect — and consistency is more than enough.', category: 'Identity', pinned: false },
      { id: 'aff19', text: 'I do not shrink under pressure. I was built for this.', category: 'Identity', pinned: false },
      { id: 'aff20', text: 'I nourish my body because it is the only home I will ever live in.', category: 'Health', pinned: false },
      { id: 'aff21', text: 'Progress is happening in my body even when I cannot see it yet.', category: 'Health', pinned: false },
      { id: 'aff22', text: 'Rest is not laziness. Rest is how I protect my output.', category: 'Health', pinned: false },
      { id: 'aff23', text: 'I am a woman of discipline, faith, and follow-through.', category: 'Identity', pinned: false },
      { id: 'aff24', text: 'I protect my peace the same way I protect everything else I love.', category: 'Identity', pinned: false },
      { id: 'aff25', text: 'I don\'t shrink in rooms. I fill them with purpose.', category: 'Identity', pinned: false },
    ],
    devotionBiblePlan: { goal: [], completedBooks: [], readingLog: [] },

    // ── Today ────────────────────────────────────────────────────────────────
    todayBrainDump: [],
    todaySleepLog: {},
    todayKitchenCheck: {},
    journalWins: [],

    // ── Silk Collective — Hair Education ─────────────────────────────────────
    scHairEducation: { filmed: {} },
  };
}
