export const THEMES = {
  strawberry: {
    label: "Strawberry Cream",
    swatches: ["#fdf3ef", "#e8527a", "#f4a261", "#88b896", "#b39bd8"],
    vars: {
      "--bg": "#fdf3ef",
      "--bg-soft": "#fbe7e0",
      "--card": "#ffffff",
      "--card-2": "#fff7f3",
      "--ink": "#3a1d28",
      "--ink-soft": "#6b4250",
      "--muted": "#a98591",
      "--line": "#f3d9d9",
      "--line-soft": "#f7e7e7",
      "--primary": "#e8527a",
      "--primary-soft": "#fbd7e1",
      "--primary-deep": "#b1325c",
      "--accent-1": "#f4a261",
      "--accent-1-soft": "#fde3cf",
      "--accent-2": "#88b896",
      "--accent-2-soft": "#d8ecdc",
      "--accent-3": "#b39bd8",
      "--accent-3-soft": "#ebe1f5",
      "--accent-4": "#f7c548",
      "--accent-4-soft": "#fdecbc",
    },
  },
  cottoncandy: {
    label: "Cotton Candy",
    swatches: ["#fbf2f7", "#f48fb1", "#a8d8f0", "#c7b8ea", "#fbd9c5"],
    vars: {
      "--bg": "#fbf2f7",
      "--bg-soft": "#f6e1ee",
      "--card": "#ffffff",
      "--card-2": "#fdf4f9",
      "--ink": "#3d1e35",
      "--ink-soft": "#6b3f5e",
      "--muted": "#b39ab0",
      "--line": "#f1d8e5",
      "--line-soft": "#f7e7ef",
      "--primary": "#f48fb1",
      "--primary-soft": "#fbe0eb",
      "--primary-deep": "#c4658a",
      "--accent-1": "#fbb286",
      "--accent-1-soft": "#fde3cf",
      "--accent-2": "#a8d8f0",
      "--accent-2-soft": "#daedf8",
      "--accent-3": "#c7b8ea",
      "--accent-3-soft": "#ece5f7",
      "--accent-4": "#fcdd8c",
      "--accent-4-soft": "#fdf1cd",
    },
  },
  hibiscus: {
    label: "Hibiscus",
    swatches: ["#fff5f7", "#d6336c", "#ff8c69", "#f4a261", "#b08bd1"],
    vars: {
      "--bg": "#fff5f7",
      "--bg-soft": "#ffe0e8",
      "--card": "#ffffff",
      "--card-2": "#fff0f4",
      "--ink": "#2d0a1a",
      "--ink-soft": "#5e2238",
      "--muted": "#a8758a",
      "--line": "#f4d0dc",
      "--line-soft": "#fae0e8",
      "--primary": "#d6336c",
      "--primary-soft": "#fbcfdd",
      "--primary-deep": "#931f49",
      "--accent-1": "#ff8c69",
      "--accent-1-soft": "#ffd9c9",
      "--accent-2": "#8eb89a",
      "--accent-2-soft": "#d6ecdc",
      "--accent-3": "#b08bd1",
      "--accent-3-soft": "#e6d9f0",
      "--accent-4": "#f5b942",
      "--accent-4-soft": "#fce4ba",
    },
  },
  peony: {
    label: "Peony Garden",
    swatches: ["#f5f0ed", "#c4658a", "#7d9b6f", "#cda678", "#a8c9b3"],
    vars: {
      "--bg": "#f5f0ed",
      "--bg-soft": "#ede0d8",
      "--card": "#ffffff",
      "--card-2": "#faf5f2",
      "--ink": "#2d2422",
      "--ink-soft": "#5c4944",
      "--muted": "#a89c95",
      "--line": "#e6d8d0",
      "--line-soft": "#ede2db",
      "--primary": "#c4658a",
      "--primary-soft": "#f1d4df",
      "--primary-deep": "#8a4063",
      "--accent-1": "#cda678",
      "--accent-1-soft": "#ecd9bd",
      "--accent-2": "#7d9b6f",
      "--accent-2-soft": "#d3dfcb",
      "--accent-3": "#a8c9b3",
      "--accent-3-soft": "#d9e8de",
      "--accent-4": "#e0b95d",
      "--accent-4-soft": "#f4e0a3",
    },
  },
  lavender: {
    label: "Lavender Plum",
    swatches: ["#f6f3fa", "#9b6dc9", "#e87aa6", "#b09bd6", "#f2c08c"],
    vars: {
      "--bg": "#f6f3fa",
      "--bg-soft": "#ebe2f0",
      "--card": "#ffffff",
      "--card-2": "#f8f4fb",
      "--ink": "#2a1a3a",
      "--ink-soft": "#553f72",
      "--muted": "#9c87b3",
      "--line": "#e4d8ed",
      "--line-soft": "#eee5f3",
      "--primary": "#9b6dc9",
      "--primary-soft": "#e2d2f0",
      "--primary-deep": "#6a4093",
      "--accent-1": "#e87aa6",
      "--accent-1-soft": "#fbd8e4",
      "--accent-2": "#8eb89a",
      "--accent-2-soft": "#d8ecdc",
      "--accent-3": "#b09bd6",
      "--accent-3-soft": "#e2d8f0",
      "--accent-4": "#f2c08c",
      "--accent-4-soft": "#fbe2c8",
    },
  },
};

export function applyTheme(themeKey) {
  const theme = THEMES[themeKey] || THEMES.strawberry;
  const root = document.documentElement;
  Object.entries(theme.vars).forEach(([k, v]) => root.style.setProperty(k, v));
}
